### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-entities#6]
In the next weeks make sure:
- [ ] the entities in baserow are accurate and up to date
- [ ] scan the documents for false tags or entities that need to be tagged
- [ ] start tagging events
